openapi: 3.0.0
info:
  title: Jobs API
  description: A simple API for managing jobs.
  version: 1.0.0
servers:
  - url: http://localhost:5000/api/v1
    description: Local server

paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User created
        '400':
          description: Bad request
          
  /auth/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '401':
          description: Unauthorized

  /jobs:
    get:
      summary: Get all jobs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of jobs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    position:
                      type: string
                    company:
                      type: string
                    status:
                      type: string
        '401':
          description: Unauthorized

    post:
      summary: Create a new job
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                position:
                  type: string
                company:
                  type: string
                status:
                  type: string
      responses:
        '201':
          description: Job created
        '400':
          description: Bad request
        '401':
          description: Unauthorized

  /jobs/{id}:
    get:
      summary: Get a single job
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The job ID
      responses:
        '200':
          description: Job details
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  position:
                    type: string
                  company:
                    type: string
                  status:
                    type: string
        '404':
          description: Job not found
        '401':
          description: Unauthorized

    patch:
      summary: Update a job
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The job ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                position:
                  type: string
                company:
                  type: string
                status:
                  type: string
      responses:
        '200':
          description: Job updated
        '400':
          description: Bad request
        '404':
          description: Job not found
        '401':
          description: Unauthorized

    delete:
      summary: Delete a job
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The job ID
      responses:
        '200':
          description: Job deleted
        '404':
          description: Job not found
        '401':
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT